[functions]
directory = "functions"
included_files = ["data/members.json"]

[[redirects]]
from = "/next"
query = {via = ":via"}
to = "/.netlify/functions/next?via=:via"
status = 301
force = true

[[redirects]]
from = "/previous"
query = {via = ":via"}
to = "/.netlify/functions/previous?via=:via"
status = 301
force = true

[[redirects]]
from = "/random"
query = {via = ":via"}
to = "/.netlify/functions/random?via=:via"
status = 301
force = true